#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sdkRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(sdkRoot, "..", "..");
const openapiPath = path.join(repoRoot, "packages", "shared", "contracts", "openapi", "v1.json");
const outputPath = path.join(sdkRoot, "src", "generated", "openapi-types.ts");

function toTypeName(input) {
  return input
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_([a-zA-Z0-9])/g, (_, ch) => ch.toUpperCase())
    .replace(/^([a-z])/, (_, ch) => ch.toUpperCase()) || "Unknown";
}

function main() {
  if (!fs.existsSync(openapiPath)) {
    throw new Error(`OpenAPI file not found: ${openapiPath}`);
  }

  const spec = JSON.parse(fs.readFileSync(openapiPath, "utf8"));
  const paths = Object.entries(spec.paths ?? {});

  const pathLiterals = paths.map(([route]) => `  | ${JSON.stringify(route)}`).join("\n");
  const methodMapLines = [];
  const operationLines = [];

  for (const [route, methods] of paths) {
    const methodNames = Object.keys(methods ?? {}).map((m) => m.toUpperCase());
    const methodLiteral = methodNames.length
      ? methodNames.map((m) => JSON.stringify(m)).join(" | ")
      : "never";
    methodMapLines.push(`  ${JSON.stringify(route)}: ${methodLiteral};`);

    for (const [method, operation] of Object.entries(methods ?? {})) {
      const operationId = operation?.operationId ?? `${method}_${toTypeName(route)}`;
      operationLines.push(`  ${JSON.stringify(operationId)}: { method: ${JSON.stringify(method.toUpperCase())}; path: ${JSON.stringify(route)} };`);
    }
  }

  const content = `/* eslint-disable */
// Auto-generated by packages/sdk/scripts/generate-types.mjs
// Source: packages/shared/contracts/openapi/v1.json

export type ApiV1Path =
${pathLiterals || "  | never"};

export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiMethodByPath = {
${methodMapLines.join("\n")}
};

export type ApiOperationById = {
${operationLines.join("\n")}
};

export type ApiOperationId = keyof ApiOperationById;

export type ApiResponse<T = unknown> = {
  status: number;
  headers: Headers;
  data: T;
};
`;

  fs.writeFileSync(outputPath, content, "utf8");
  console.log(`Generated ${path.relative(repoRoot, outputPath)}`);
}

main();
