ALTER TABLE "Rollout"
  ADD COLUMN "strategy" TEXT NOT NULL DEFAULT 'BATCH',
  ADD COLUMN "canarySteps" INTEGER[] NOT NULL DEFAULT ARRAY[5,25,100],
  ADD COLUMN "canaryStepWaitSec" INTEGER NOT NULL DEFAULT 120,
  ADD COLUMN "sloP95Max" DOUBLE PRECISION,
  ADD COLUMN "sloErrorRateMax" DOUBLE PRECISION,
  ADD COLUMN "sloWebhookRetryRateMax" DOUBLE PRECISION,
  ADD COLUMN "autoRollback" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "UpdateJob"
  ADD COLUMN "canaryPercent" INTEGER,
  ADD COLUMN "metricP95Ms" DOUBLE PRECISION,
  ADD COLUMN "metricErrorRate" DOUBLE PRECISION,
  ADD COLUMN "metricWebhookRetryRate" DOUBLE PRECISION,
  ADD COLUMN "meta" JSONB;
